# 1. Build stage
FROM node:20 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install --silent
COPY . .
RUN npm run build

# 2. Production stage
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

# docker run \
#     --name mern-frontend \
#     --network mern-net \
#     -p 80:80 \
#     -e VITE_BACKEND_URL="http://mern-backend:8000" \
#     frontend